/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttrsChild: typeof import('./src/components/depth/AttrsChild.vue')['default']
    AttrsGrandChild: typeof import('./src/components/depth/AttrsGrandChild.vue')['default']
    ChildPropseEmits: typeof import('./src/components/depth/ChildPropseEmits.vue')['default']
    copy: typeof import('./src/components/depth/AttrsChild copy.vue')['default']
    CustomInput: typeof import('./src/components/depth/CustomInput.vue')['default']
    Dashboard: typeof import('./src/components/other/Dashboard.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    MittChild1: typeof import('./src/components/depth/MittChild1.vue')['default']
    MittChild2: typeof import('./src/components/depth/MittChild2.vue')['default']
    Modal: typeof import('./src/components/other/Modal.vue')['default']
    PropsAndEmitsChild: typeof import('./src/components/depth/PropsAndEmitsChild.vue')['default']
    ProvideChild: typeof import('./src/components/depth/ProvideChild.vue')['default']
    ProvideGrandChild: typeof import('./src/components/depth/ProvideGrandChild.vue')['default']
    RefAndParentChild1: typeof import('./src/components/depth/RefAndParentChild1.vue')['default']
    RefAndParentChild2: typeof import('./src/components/depth/RefAndParentChild2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotDefine: typeof import('./src/components/depth/SlotDefine.vue')['default']
    SlotFruits: typeof import('./src/components/depth/SlotFruits.vue')['default']
  }
}
