/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/Content.vue')['default']
    Count: typeof import('./src/components/Count.vue')['default']
    CustomInput: typeof import('./src/components/basic/CustomInput.vue')['default']
    CustomRef: typeof import('./src/components/CustomRef.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    LoveTalk: typeof import('./src/components/LoveTalk.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    Modal: typeof import('./src/components/other/Modal.vue')['default']
    PropsAndEmitsChild: typeof import('./src/components/basic/PropsAndEmitsChild.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotDefine: typeof import('./src/components/depth/SlotDefine.vue')['default']
    SlotFruits: typeof import('./src/components/depth/SlotFruits.vue')['default']
  }
}
